# Generated by Django 4.1.1 on 2022-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('phoned', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Youtube', 'Youtube')], max_length=250)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('special_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
