# Generated by Django 4.1.1 on 2022-09-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='dis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
